const STORAGE_KEY = "zhiyun-campus-v3";
const legacyKey = "xiaoyu-campus-opportunities-v1";
const seedOpportunities = [
  {id:"bridge-camp",title:"“蓝桥杯”程序设计校内训练营",category:"学习",source:"学校",status:"报名中",time:"9月21日 19:30 起",location:"实验楼 A402",capacity:"零基础可参加",contact:"校内训练营报名入口",description:"场地调整后的首次训练时间为 9 月 21 日 19:30，请以本条补充信息为准。",updated:true,views:628,likes:82,follows:47},
  {id:"ai-class",title:"AI应用入门公开课",category:"学习",source:"学院",status:"即将开始",time:"9月19日 19:00",location:"计算机学院教学楼",capacity:"预计 90 分钟",contact:"无需报名",description:"面向全校学生的 AI 应用入门公开课，无需提前报名。",views:492,likes:66,follows:31},
  {id:"startup-team",title:"大学生创新创业项目团队招募",category:"招募",source:"学校",status:"报名中",time:"9月22日 18:00 截止",location:"线上投递",capacity:"设计、材料成员",contact:"提交简短自我介绍",description:"开发方向名额已满，目前主要补充设计与材料成员；每周预计投入 4 小时。",updated:true,views:561,likes:73,follows:59},
  {id:"volunteer",title:"校园公益志愿服务活动",category:"活动",source:"学校",status:"即将截止",time:"9月27日 8:30—17:00",location:"待通知",capacity:"预计服务 8 小时",contact:"9月20日 12:00 前报名",description:"需要提前到场签到；适合希望参与校内公益服务的同学。",views:428,likes:51,follows:38},
  {id:"ai-challenge",title:"AI创新应用挑战赛",category:"比赛",source:"学院",status:"报名中",time:"9月21日 18:00 前",location:"校内意向登记",capacity:"2—4 人组队",contact:"赛事意向登记入口",description:"意向登记不等同于最终作品提交，正式作品提交截止到 10 月 20 日。",views:713,likes:105,follows:92},
  {id:"git-workshop",title:"Git与GitHub零基础工作坊",category:"学习",source:"学院",status:"报名中",time:"9月21日 19:00—20:30",location:"待审核通知",capacity:"限 40 人",contact:"提前预约",description:"主要面向大一新生；提交报名表不代表最终录取，请等待审核通知。",views:686,likes:118,follows:76},
  {id:"badminton",title:"周末羽毛球约球",category:"活动",source:"学生",status:"待确认",time:"9月20日 16:00",location:"场地待最终确认",capacity:"计划 6—8 人",contact:"在站内留言",description:"学生个人发起，费用 AA。场地尚未确认，建议参与前先留言核实。",views:166,likes:19,follows:13},
  {id:"study-buddy",title:"AI工具交流搭子招募",category:"招募",source:"学生",status:"待确认",time:"9月21日晚上",location:"地点未确定",capacity:"欢迎零基础",contact:"报名后拉群",description:"学生个人发起的 AI 工具交流活动，地点将在成团后确认。",views:241,likes:28,follows:21}
];
const $ = (s) => document.querySelector(s); const $$ = (s) => [...document.querySelectorAll(s)];
let activeCategory="全部",activeSource="全部",sortMode="smart",selectedId=null,toastTimer;
function loadState(){ try { const now=JSON.parse(localStorage.getItem(STORAGE_KEY)); const old=JSON.parse(localStorage.getItem(legacyKey)); return {user:now?.user??old?.user??null,favorites:now?.favorites??old?.favorites??[],interested:now?.interested??old?.interested??[],published:now?.published??old?.published??[],pinned:now?.pinned??[],engagement:now?.engagement??{}}; } catch { return {user:null,favorites:[],interested:[],published:[],pinned:[],engagement:{}}; } }
let state=loadState(); function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));} function allItems(){return [...state.published,...seedOpportunities];}
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#039;","\"":"&quot;"}[c]));} function initials(n){return n?[...n][0]:"访";} function sourceClass(s){return ({学校:"school",学院:"college",学生:"student"})[s]||"student";} function statusClass(s){return s.includes("截止")?"soon":s.includes("确认")?"pending":"open";}
function metric(item){const m=state.engagement[item.id]||{};return {views:m.views??item.views??0,likes:m.likes??item.likes??0,follows:m.follows??item.follows??0,liked:!!m.liked,followed:!!m.followed};} function score(item){const m=metric(item);return m.likes*7+m.follows*6+Math.min(m.views,900)*.12+(item.source!=="学生"?18:0)+(item.status.includes("确认")?-16:0);} function saveMetric(id,patch){state.engagement[id]={...(state.engagement[id]||{}),...patch};save();}
function ordered(items,mode=sortMode){return [...items].sort((a,b)=>{const pin=(state.pinned.includes(b.id)?1:0)-(state.pinned.includes(a.id)?1:0);if(pin)return pin;if(mode==="hot")return metric(b).views-metric(a).views;if(mode==="useful")return score(b)-score(a);return score(b)-score(a);});}
function renderHeader(){const n=state.user?.name||"访客";$("#headerAvatar").textContent=initials(n);$("#headerUserName").textContent=n;$("#headerIdentity").textContent=state.user?.identity||"点击绑定校园身份";$("#mobileAccount").textContent=initials(n);}
function renderDrawer(){const root=$("#drawerContent");if(!state.user){root.innerHTML=`<div class="drawer-inner"><h3>尚未绑定身份</h3><p>绑定昵称后，可发布信息、点赞、关注与置顶内容。</p><button class="drawer-action primary" data-drawer="bind">绑定校园身份</button></div>`;return;}const fav=state.favorites.length,follow=state.interested.length,pub=state.published.length;root.innerHTML=`<div class="drawer-inner"><h3>${esc(state.user.name)}</h3><p>${esc(state.user.identity||"已绑定校园身份")}</p><div class="drawer-stats"><div class="drawer-stat"><strong>${fav}</strong><span>收藏</span></div><div class="drawer-stat"><strong>${follow}</strong><span>关注</span></div><div class="drawer-stat"><strong>${pub}</strong><span>发布</span></div></div><button class="drawer-action primary" data-drawer="profile">查看我的清单</button><button class="drawer-action" data-drawer="bind">编辑身份信息</button></div>`;}
function renderFilters(){const cats=["全部","活动","学习","招募","比赛"],sources=["全部","学校","学院","学生"];$("#categoryFilters").innerHTML=cats.map(x=>`<button class="filter-chip ${x===activeCategory?"is-selected":""}" data-category="${x}">${x}</button>`).join("");$("#sourceFilters").innerHTML=sources.map(x=>`<button class="filter-chip ${x===activeSource?"is-selected":""}" data-source="${x}">${x==="全部"?"全部来源":x+"发布"}</button>`).join("");$$('.sort-button').forEach(b=>b.classList.toggle('is-selected',b.dataset.sort===sortMode));}
function filtered(){const q=$("#searchInput").value.trim().toLowerCase();return allItems().filter(x=>(activeCategory==="全部"||x.category===activeCategory)&&(activeSource==="全部"||x.source===activeSource)&&(!q||`${x.title} ${x.description} ${x.location}`.toLowerCase().includes(q)));}
function card(item){const m=metric(item),pinned=state.pinned.includes(item.id);return `<button class="opportunity-card" data-detail="${item.id}">${pinned?'<span class="pin-mark">⌖</span>':''}<span class="card-meta"><span class="tag ${sourceClass(item.source)}">${esc(item.source)}发布</span><span class="tag">${esc(item.category)}</span><span class="status ${statusClass(item.status)}">${esc(item.status)}</span></span><h3>${esc(item.title)}</h3><p>${esc(item.description)}</p><div class="card-bottom"><div class="card-facts"><span>◷ ${esc(item.time)}</span><span>⌖ ${esc(item.location)}</span></div><div class="engagement"><span>浏览 <strong>${m.views}</strong></span><span>点赞 <strong>${m.likes}</strong></span><span>关注 <strong>${m.follows}</strong></span></div></div></button>`;}
function renderLists(){const data=ordered(filtered());$("#resultCount").textContent=`共 ${data.length} 条`;$("#opportunityList").innerHTML=data.map(card).join("");$("#discoverEmpty").classList.toggle("hidden",!!data.length);const good=allItems().filter(x=>score(x)>=400).length;$("#usefulCount").textContent=good;$("#featuredList").innerHTML=ordered(allItems(),"useful").slice(0,6).map(card).join("");}
function renderPublishHint(){$("#publishBindingHint").innerHTML=state.user?`<div class="hint-card"><span>将以 <strong>${esc(state.user.name)}</strong> 的身份发布，发布后可在左侧账号抽屉中管理。</span><button class="text-button" data-drawer="bind">切换身份</button></div>`:`<div class="hint-card"><span><strong>发布前请先绑定身份。</strong> 绑定后可管理发布、点赞、关注和置顶信息。</span><button class="text-button" data-drawer="bind">去绑定</button></div>`;}
function mini(items){return items.length?`<div class="mini-list">${items.map(x=>`<div class="mini-item"><div><strong>${esc(x.title)}</strong><span>${esc(x.status)} · ${esc(x.time)}</span></div><button class="text-button" data-detail="${x.id}">查看</button></div>`).join("")}</div>`:"<p class=\"form-note\">还没有内容，去发现页看看吧。</p>";}
function renderProfile(){const root=$("#profileContent");if(!state.user){root.innerHTML=`<div class="profile-panel"><p class="eyebrow">我的校园清单</p><h1>绑定身份后开始管理</h1><p class="description">你可以发布信息、收藏活动、关注话题，并把真正有用的内容置顶。</p><button class="primary-button" data-drawer="bind">绑定校园身份</button></div>`;return;}root.innerHTML=`<div class="profile-panel"><p class="eyebrow">${esc(state.user.name)} 的校园清单</p><h1>我关注的机会</h1><p class="description">收藏、关注和自己发布的信息都会保存到当前浏览器。</p><h3>收藏的信息</h3>${mini(allItems().filter(x=>state.favorites.includes(x.id)))}<h3>我发布的信息</h3>${mini(state.published)}</div>`;}
function showView(view){$$('.view').forEach(x=>x.classList.toggle('is-active',x.id===view+'View'));$$('.side-nav-item').forEach(x=>x.classList.toggle('is-active',x.dataset.view===view));if(view==='profile')renderProfile();if(view==='publish')renderPublishHint();window.scrollTo({top:0,behavior:'smooth'});}
function toggleDrawer(){const d=$("#accountDrawer"),open=d.hidden;d.hidden=!open;$("#accountTrigger").setAttribute('aria-expanded',String(open));renderDrawer();} function openBind(){const d=$("#bindDialog");d.querySelector('[name=name]').value=state.user?.name||"";d.querySelector('[name=identity]').value=state.user?.identity||"";d.showModal();}function requireUser(){if(state.user)return true;showToast('请先绑定身份，再保存操作');openBind();return false;} function showToast(t){const x=$("#toast");x.textContent=t;x.classList.add('is-visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>x.classList.remove('is-visible'),2100);}
function openDetail(id){const item=allItems().find(x=>x.id===id);if(!item)return;selectedId=id;const before=metric(item);saveMetric(id,{views:before.views+1});const m=metric(item),fav=state.favorites.includes(id),pin=state.pinned.includes(id);$("#detailContent").innerHTML=`<div class="card-meta"><span class="tag ${sourceClass(item.source)}">${esc(item.source)}发布</span><span class="tag">${esc(item.category)}</span><span class="status ${statusClass(item.status)}">${esc(item.status)}</span></div><h2>${esc(item.title)}</h2><p class="description">${esc(item.description)}</p><div class="detail-facts"><div class="fact"><span>时间</span><strong>${esc(item.time)}</strong></div><div class="fact"><span>地点</span><strong>${esc(item.location)}</strong></div><div class="fact"><span>参与条件</span><strong>${esc(item.capacity||'以发布信息为准')}</strong></div><div class="fact"><span>参与方式</span><strong>${esc(item.contact)}</strong></div></div><div class="engagement"><span>浏览 <strong>${m.views}</strong></span><span>点赞 <strong>${m.likes}</strong></span><span>关注 <strong>${m.follows}</strong></span></div><div class="detail-actions"><button class="primary-button" data-action="like">${m.liked?'已点赞':'点赞'}</button><button class="secondary-button" data-action="follow">${m.followed?'已关注':'关注'}</button><button class="secondary-button" data-action="favorite">${fav?'已收藏':'收藏'}</button><button class="secondary-button" data-action="pin">${pin?'取消置顶':'置顶信息'}</button></div>`;$("#detailDialog").showModal();renderLists();}
function action(name){const item=allItems().find(x=>x.id===selectedId);if(!item||!requireUser())return;const m=metric(item);if(name==='like'){saveMetric(item.id,{liked:!m.liked,likes:m.likes+(m.liked?-1:1)});showToast(m.liked?'已取消点赞':'已点赞');}if(name==='follow'){saveMetric(item.id,{followed:!m.followed,follows:m.follows+(m.followed?-1:1)});state.interested=m.followed?state.interested.filter(x=>x!==item.id):[...new Set([...state.interested,item.id])];save();showToast(m.followed?'已取消关注':'已关注');}if(name==='favorite'){state.favorites=state.favorites.includes(item.id)?state.favorites.filter(x=>x!==item.id):[...state.favorites,item.id];save();showToast(state.favorites.includes(item.id)?'已收藏':'已取消收藏');}if(name==='pin'){state.pinned=state.pinned.includes(item.id)?state.pinned.filter(x=>x!==item.id):[item.id,...state.pinned];save();showToast(state.pinned.includes(item.id)?'信息已置顶':'已取消置顶');}renderDrawer();renderLists();openDetail(item.id);}
function dateText(v){const d=new Date(v);return `${d.getMonth()+1}月${d.getDate()}日 ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;}
function bind(){ $("#searchInput").addEventListener('input',renderLists);document.addEventListener('click',e=>{const view=e.target.closest('[data-view]');if(view)showView(view.dataset.view);const cat=e.target.closest('[data-category]');if(cat){activeCategory=cat.dataset.category;renderFilters();renderLists();}const src=e.target.closest('[data-source]');if(src){activeSource=src.dataset.source;renderFilters();renderLists();}const sort=e.target.closest('[data-sort]');if(sort){sortMode=sort.dataset.sort;renderFilters();renderLists();}const detail=e.target.closest('[data-detail]');if(detail)openDetail(detail.dataset.detail);const drawer=e.target.closest('[data-drawer]');if(drawer){if(drawer.dataset.drawer==='bind')openBind();if(drawer.dataset.drawer==='profile'){showView('profile');if(!$("#accountDrawer").hidden)toggleDrawer();}}if(e.target.id==='clearFilters'){activeCategory='全部';activeSource='全部';$("#searchInput").value='';renderFilters();renderLists();}if(e.target.dataset.action)action(e.target.dataset.action);});$("#accountTrigger").addEventListener('click',toggleDrawer);$("#mobileAccount").addEventListener('click',openBind);$("#closeDetail").addEventListener('click',()=>$("#detailDialog").close());$("#closeBind").addEventListener('click',()=>$("#bindDialog").close());$("#bindForm").addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.user={name:f.get('name').trim(),identity:f.get('identity').trim()};save();renderHeader();renderDrawer();renderPublishHint();renderProfile();$("#bindDialog").close();showToast('身份绑定成功');});$("#publishForm").addEventListener('submit',e=>{e.preventDefault();if(!requireUser())return;const f=new FormData(e.currentTarget),id='user-'+Date.now();state.published.unshift({id,title:f.get('title').trim(),category:f.get('category'),source:'学生',status:'待确认',time:dateText(f.get('time')),location:f.get('location').trim(),capacity:f.get('capacity').trim()||'人数待确认',contact:f.get('contact').trim(),description:f.get('description').trim(),views:0,likes:0,follows:0});save();e.currentTarget.reset();renderLists();renderDrawer();showView('discover');showToast('发布成功，已进入信息流');});}
function init(){renderHeader();renderDrawer();renderFilters();renderLists();renderPublishHint();renderProfile();bind();}init();